version: '3.7'

services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - REDIS_URL=${REDIS_URL}
      - URL=http://outline.a246004.org # Outline base URL
      - COLLABORATION_URL=http://localhost:3000/collaboration  # Collaboration URL
      - PGSSLMODE=disable  # Disable SSL (adjust based on your setup)
      - FORCE_HTTPS=false  # Disable HTTPS (adjust based on your needs)
      - OIDC_CLIENT_ID=outline-client
      - OIDC_AUTH_URI=http://auth.a246004.org/login/oauth/authorize
      - OIDC_TOKEN_URI=http://casdoor:8000/api/login/oauth/access_token
      - OIDC_USERINFO_URI=http://casdoor:8000/api/userinfo
      - OIDC_CLIENT_SECRET=6cb009ffe5fba17883b432130d83512f30f41e1c
    networks:
      - my_network
    ports:
      - "3000:3000" # Expose Outline on port 3000 to other containers (not to the host directly)

  casdoor:
    image: casbin/casdoor-all-in-one
    container_name: casdoor
    ports:
      - "8000:8000"
    environment:
      - CASDOOR_UI_URL=http://localhost:8000
      - CASDOOR_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./casdoor:/conf
    networks:
      - my_network
    restart: always

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"

  redis:
    image: redis
    networks:
      - my_network
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    networks:
      - my_network
    command: server /data --console-address ":9090"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
    depends_on:
      - outline
      - casdoor

networks:
  my_network:
    driver: bridge
