version: '3.7'

services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - REDIS_URL=${REDIS_URL}
      - URL=http://outline.a246004.org  # Outline base URL
      - COLLABORATION_URL=http://localhost:3000/collaboration  # Collaboration URL
      - PGSSLMODE=disable  # Disable SSL (adjust based on your setup)
      - FORCE_HTTPS=false  # Disable HTTPS (adjust based on your needs)
      - OIDC_CLIENT_ID=outline-client
      - OIDC_AUTH_URI=http://auth.a246004.org/login/oauth/authorize
      - OIDC_TOKEN_URI=http://casdoor:8000/api/login/oauth/access_token
      - OIDC_USERINFO_URI=http://casdoor:8000/api/userinfo
      - OIDC_CLIENT_SECRET=6cb009ffe5fba17883b432130d83512f30f41e1c
    ports:
      - 3000:3000  # Expose Outline on port 3000
    depends_on:
      - postgres
      - minio
      - redis
    networks:
      - my_network
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --protocol http2 run --token eyJhIjoiN2UyODczNjcyN2Y1MjQyYWJlZWY2NWNiNGJhOGJhZjAiLCJ0IjoiZGM2NzE1ZGQtMTVjZi00OWEyLTk3ZGYtNWQzNzRmYTY5YmEzIiwicyI6Ik9HRXdPV1F5TlRFdE5tSm1OaTAwTXpnNExXSmxZamN0WVRsa01UVmtOVFJrWVRVeSJ9
    restart: always
    networks:
      - my_network

  casdoor:
    image: casbin/casdoor-all-in-one
    container_name: casdoor
    ports:
      - "8000:8000"  # 映射本地 8000 端口到容器 8000 端口
    environment:
      - CASDOOR_UI_URL=http://localhost:8000
      - CASDOOR_API_URL=http://localhost:8000/api/v1
    volumes:
      - /tmp/outline/casdoor:/conf
    networks:
      - my_network
    restart: always

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - /tmp/outline/postgres/data:/var/lib/postgresql/data  # Persistent Postgres data
    networks:
      - my_network
    ports:
      - "5432:5432"  # Expose Postgres on port 5432

  redis:
    image: redis
    networks:
      - my_network
    ports:
      - "6379:6379"  # Expose Redis on port 6379

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"  # Expose Minio on port 9000
      - "9090:9090"  # Expose Minio console on port 9090
    volumes:
      - /tmp/outline/minio/data:/data  # Persistent Minio data
      - /tmp/outline/minio/config:/root/.minio  # Minio config
    networks:
      - my_network
    command: server /data --console-address ":9090"

networks:
  my_network:
    driver: bridge